feat: add nix flake
ryanccn/valfisk pull request #1
Opened 2023-10-17 13:39 UTC by getchoo

this adds a standard nix flake for building both the binary and docker image - all with cross compiling from macos -> linux and a dev shell!

you should probably test the docker image though since i haven't tried it, along with the `cross.x86_64/aarch64-darwin.x86_64-linux.valfisk` outputs

2023-10-26 09:19 UTC, ryanccn requested changes
Cross-compilation from darwin does not work; outputs darwin executable

2023-10-28 02:22 UTC, ryanccn commented
Building `valfisk-docker` on macOS still results in a macOS Mach-O binary in a Linux Docker image. Is there any way around this?

Also, how are you supposed to use the `cross` packages? Doing `nix build .#legacyPackages.x86_64-linux.cross.valfisk` didn't really work for me.

2023-10-28 13:20 UTC, getchoo commented
> Building valfisk-docker on macOS still results in a macOS Mach-O binary in a Linux Docker image. Is there any way around this?

for some reason i thought this would make a macos docker image...lol
anyways, i've made a new set of packages in `legacyPackages` (since they really shouldn't be used outside of this flake) that will build a static version of valfisk for linux from any system, along with an accompanying docker image. you can build these with `nix build .#valfisk-static` and `nix build .#valfisk-docker`

> Also, how are you supposed to use the cross packages? Doing nix build .#legacyPackages.x86_64-linux.cross.valfisk didn't really work for me.

see above; i've slightly changed the approach here since we only really need these for docker images and compiling to a static linux binary

2023-11-08 23:59 UTC, ryanccn requested changes

2023-11-08 23:59 UTC, ryanccn commented on .github/workflows/docker.yml
> +          docker push "${{ env.TAG }}"
This makes the image not multi-platform!

2023-11-09 03:36 UTC, getchoo commented on .github/workflows/docker.yml
> +          docker push "${{ env.TAG }}"
i think i fixed this, but let me know since i'm not super familiar lol

2023-11-20 10:34 UTC, ryanccn commented on nix/docker.nix
> +        name = "ryanccn/valfisk";
The image name should probably be `valfisk`, since the username is more of a GItHub Container Registry thing

2023-11-20 10:35 UTC, ryanccn commented on nix/derivation.nix
> +  optimizeSize ? false,
Could turn this on for the Docker image

2023-12-02 02:35 UTC, ryanccn commented
rip

2023-12-02 03:45 UTC, merged